### ISSUE TITLE
MPRIS doesn't  work

### ISSUE THREAD

**Issue by bil-elmoussaoui** [flathub/com.github.needleandthread.vocal#2]
I have just tried to use Vocal with Flatpak. And it seems that MPRIS doesn't  work at all :(
I can't get the currently played podcast notification to show up on Gnome notification center(or whatever it's called)

**Comment by TingPing** [comment]
Just missing permissions to own the mpris bus name.

**Comment by Alexander-Wilms** [comment]
Should be fixed now

**Comment by bil-elmoussaoui** [comment]
Fixed, thanks :+1:
