### ISSUE TITLE
2.4 Update

### ISSUE THREAD

**Issue by nathandyer** [flathub/com.github.needleandthread.vocal#7]
Hi! Just wanted to let you all know that Vocal is [now on version 2.4](https://github.com/needle-and-thread/vocal/releases/tag/2.4.0). What needs to be done to get the update uploaded to Flathub? Also, can we remove the patch that forces the elementary GTK and icon themes? On non-elementary platforms I'd prefer it to use the standard system themes.

Thanks everyone!

**Comment by bilelmoussaoui** [comment]
This was fixed already
